name:                day04
version:             0.1.0.0
github:              "mdm/day04"
license:             BSD3
author:              "Marc Dominik Migge"
maintainer:          "marcmigge@gmx.net"
copyright:           "2021 Marc Dominik Migge"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mdm/day04#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- cryptonite

library:
  source-dirs: src

executables:
  day04-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day04

tests:
  day04-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - day04
